services:
  - type: web
    name: tu-zona-de-descargas-ec
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 4 app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
